spring.application.name=ShopEase
server.port=8000

spring.data.mongodb.uri=mongodb://localhost:27017/shopease

# MySQL Config (Custom)
# --------------------
spring.datasource.mysql.jdbcurl=jdbc:mysql://localhost:3306/shopeaseDb
spring.datasource.mysql.username=root
spring.datasource.mysql.password=12345678Dd!
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate for MySQL
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update

